#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | like rsync but for blue bear & OpenFOAM
#  \\    /   O peration     | Web: https://github.com/LeoTurnell-Ritson/bbsync
#   \\  /    A nd           |
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
#
# Description
#  Basic make script using pyinstaller
#  (see https://pypi.org/project/pyinstaller/)
#
#------------------------------------------------------------------------------

pyinstaller --clean -F src/bbsync.py -n bbsync

# ----------------------------------------------------------------- end-of-file
